from .extraction import OPENAI_EXTRACTION_PROMPT, POST_PROMPT_INSTR
from .email import EMAIL_SYSTEM_PROMPT, EMAIL_TEMPLATE

__all__ = ['OPENAI_EXTRACTION_PROMPT', 'POST_PROMPT_INSTR', 'EMAIL_SYSTEM_PROMPT', 'EMAIL_TEMPLATE']